# only values different from default-environment.yaml need to be defined here; the default config is always loaded

# Deltalinqs close to container
initial_lat: deg(51.89874799)
initial_lon: deg(4.41473191)
initial_altitude: 125.0
initial_heading: deg(187)
