# only values different from default-environment.yaml need to be defined here; the default config is always loaded

# In front of room KN:E-121 heading towards the far end of the hallway
initial_lat: deg(51.486862)
initial_lon: deg(7.484634)
initial_altitude: 210.0
initial_heading: deg(75.0)
